name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make cover

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}